### ISSUE TITLE
new location is offline

### ISSUE THREAD

**Issue by tjluoma** [coolaj86/osx-wifi-volume-remote#5]
Tried to find the newest version and received this message: 

> Safari can’t open the page “https://git.daplie.com/coolaj86/osx-wifi-volume-remote” because Safari can’t find the server “git.daplie.com”.

Looks like that host doesn't even exist:

```
% host git.daplie.com
Host git.daplie.com not found: 3(NXDOMAIN)
```

**Comment by coolaj86** [comment]
Reverted.
