### ISSUE TITLE
Question: what does the "--100%" do?

### ISSUE THREAD

**Issue by tjluoma** [coolaj86/osx-wifi-volume-remote#8]
I've seen this a couple places but no explanation.

From what I tested, it looks like 

```
set volume without output muted output volume 18
```

and

```
set volume without output muted output volume 18 --100%
```

seem to do the same thing, but I'm guessing there's a reason people use the ` --100%` but I don't know why.

**Comment by coolaj86** [comment]
I know that --100% guarantees that the value 18 will be measured as 18% (meaning 0.18).

My guess is that either it was once required to specify what system of measure to use, or there was once a different default option.

**Comment by tjluoma** [comment]
I think a long time ago it used to go 0-7, but that was a long time ago. But old habits die hard I guess.
